library(tidyverse)
library(eeptools)
library(readr)
library(genero)
#Cargar datos
BASE_DATOS_PSOCIALES_JULIO2021 <- 
        read.csv("~/R Projects/Reporte_Gerencia_BU_2021/Datos/BASE DATOS PSOCIALES B U JULIO2021.csv", header=FALSE)
#Renombrar las variables de la base de datos para conservar DPI
x <- BASE_DATOS_PSOCIALES_JULIO2021[1,]
BASE_DATOS_PSOCIALES_JULIO2021 <- BASE_DATOS_PSOCIALES_JULIO2021[-1,]
colnames(BASE_DATOS_PSOCIALES_JULIO2021) <- x[1,]
rm(x)
#Tipificar variables
BASE_DATOS_PSOCIALES_JULIO2021$ASIGNACION <- gsub(",","",BASE_DATOS_PSOCIALES_JULIO2021$ASIGNACION)
BASE_DATOS_PSOCIALES_JULIO2021$ASIGNACION <- as.factor(BASE_DATOS_PSOCIALES_JULIO2021$ASIGNACION)

BASE_DATOS_PSOCIALES_JULIO2021$ANIO <- gsub(",","",BASE_DATOS_PSOCIALES_JULIO2021$ANIO)
BASE_DATOS_PSOCIALES_JULIO2021$ANIO <- as.factor(BASE_DATOS_PSOCIALES_JULIO2021$ANIO)

BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA[BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA=="CONVIVENVIA"] <- "CONVIVENCIA"
BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA[BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA=="MUNIEDUCA MOVIL"] <- "MUNIEDUCA MÓVIL"
BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA[BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA=="TECNICO PRODUCTIVO"] <- "TÉCNICO PRODUCTIVO"
BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA <- as.factor(BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA)

BASE_DATOS_PSOCIALES_JULIO2021$CUI<- trimws(BASE_DATOS_PSOCIALES_JULIO2021$CUI, which = "both")
BASE_DATOS_PSOCIALES_JULIO2021$CUI[nchar(BASE_DATOS_PSOCIALES_JULIO2021$CUI)==12] <- NA
        #Fecha de nacimiento con formato fecha
BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO <- format(as.POSIXct(BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO,
                                                        format='%m/%d/%Y %H:%M:%S'),format='%m/%d/%Y')
BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO<- as.Date(BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO,
                                                          format = "%m/%d/%Y")
        #Eliminar fechas erradas (imposible haber nacido después de hoy)        
BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO[BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO>=Sys.Date()] <- NA
        #Limpieza de sexo
                #Obtener los que no tienen sexo y agregárselo
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[BASE_DATOS_PSOCIALES_JULIO2021$SEXO==""] <- NA
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[BASE_DATOS_PSOCIALES_JULIO2021$SEXO=="A"] <- NA
SIN_SEXO <- BASE_DATOS_PSOCIALES_JULIO2021 %>%
        filter(is.na(BASE_DATOS_PSOCIALES_JULIO2021$SEXO)) %>%
        select(CUI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,SEXO) %>%
        distinct(CUI,.keep_all=TRUE)
SIN_SEXO$SEXO <- genero(SIN_SEXO$PRIMER_NOMBRE,lang = "es")
SIN_SEXO$SEXO[SIN_SEXO$SEXO=="female"] <- "F"
SIN_SEXO$SEXO[SIN_SEXO$SEXO=="male"] <- "M"
                #Corregir el sexo de los posibles
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[BASE_DATOS_PSOCIALES_JULIO2021$CUI==2940568380101] <- "F"
                #Filtrado y reconstruccion de la bse de datos
COMPLETA_SIN_SEXO <- BASE_DATOS_PSOCIALES_JULIO2021 %>%
        filter(is.na(BASE_DATOS_PSOCIALES_JULIO2021$SEXO)) %>%
        select(CUI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,SEXO)
COMPLETA_SIN_SEXO$SEXO<- SIN_SEXO$SEXO[match(COMPLETA_SIN_SEXO$CUI,SIN_SEXO$CUI)]
x<- which(is.na(BASE_DATOS_PSOCIALES_JULIO2021$SEXO)) 
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[x] <- COMPLETA_SIN_SEXO$SEXO
rm(COMPLETA_SIN_SEXO)
rm(SIN_SEXO)
rm(x)
                #Cambio de notacion y convertir a factor
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[BASE_DATOS_PSOCIALES_JULIO2021$SEXO=="F"] <- "Femenino"
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[BASE_DATOS_PSOCIALES_JULIO2021$SEXO=="M"] <- "Masculino"
BASE_DATOS_PSOCIALES_JULIO2021$SEXO <- as.factor(BASE_DATOS_PSOCIALES_JULIO2021$SEXO)
        #Generacion de edad y grupo de edad
BASE_DATOS_PSOCIALES_JULIO2021$EDAD <- NA
CON_FECHA_NAC <- BASE_DATOS_PSOCIALES_JULIO2021 %>%
        filter(!is.na(BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO))
CON_FECHA_NAC$EDAD<- age_calc(dob = CON_FECHA_NAC$FECHA_NACIMIENTO,
         enddate = Sys.Date(),
         units = "years")
BASE_DATOS_PSOCIALES_JULIO2021$EDAD<- 
        CON_FECHA_NAC$EDAD[match(BASE_DATOS_PSOCIALES_JULIO2021$CUI,CON_FECHA_NAC$CUI)]
BASE_DATOS_PSOCIALES_JULIO2021$EDAD <- trunc(BASE_DATOS_PSOCIALES_JULIO2021$EDAD)
BASE_DATOS_PSOCIALES_JULIO2021$EDAD <- as.integer(BASE_DATOS_PSOCIALES_JULIO2021$EDAD)
BASE_DATOS_PSOCIALES_JULIO2021$EDAD[BASE_DATOS_PSOCIALES_JULIO2021$EDAD==0] <- NA
rm(CON_FECHA_NAC)
BASE_DATOS_PSOCIALES_JULIO2021$GRUPO_EDAD <- NA
BASE_DATOS_PSOCIALES_JULIO2021$GRUPO_EDAD[BASE_DATOS_PSOCIALES_JULIO2021$EDAD<15] <- "Niño(a)"
BASE_DATOS_PSOCIALES_JULIO2021$GRUPO_EDAD[14<BASE_DATOS_PSOCIALES_JULIO2021$EDAD &
                                                  BASE_DATOS_PSOCIALES_JULIO2021$EDAD<30] <- "Jóven"
BASE_DATOS_PSOCIALES_JULIO2021$GRUPO_EDAD[29<BASE_DATOS_PSOCIALES_JULIO2021$EDAD &
                                                  BASE_DATOS_PSOCIALES_JULIO2021$EDAD<60] <- "Adulto"
BASE_DATOS_PSOCIALES_JULIO2021$GRUPO_EDAD[BASE_DATOS_PSOCIALES_JULIO2021$EDAD>59] <- "Adulto mayor"
BASE_DATOS_PSOCIALES_JULIO2021$GRUPO_EDAD <- as.factor(BASE_DATOS_PSOCIALES_JULIO2021$GRUPO_EDAD)
BASE_DATOS_PSOCIALES_JULIO2021$GRUPO_EDAD <- factor(BASE_DATOS_PSOCIALES_JULIO2021$GRUPO_EDAD,
                                                    levels = c("Niño(a)","Jóven","Adulto","Adulto mayor"))
        #Limpiar zona y agregar region
BASE_DATOS_PSOCIALES_JULIO2021$ZONA[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==""] <- NA
BASE_DATOS_PSOCIALES_JULIO2021$ZONA[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==0] <- NA
BASE_DATOS_PSOCIALES_JULIO2021$ZONA[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==73] <- NA
                #Remover zonas de Mixco
x<- grep("MIXCO",BASE_DATOS_PSOCIALES_JULIO2021$DIRECCIOIN)
BASE_DATOS_PSOCIALES_JULIO2021$ZONA[x] <- NA
rm(x)
                #Remover zonas de Villanueva
x<- grep("VILLANUEVA",BASE_DATOS_PSOCIALES_JULIO2021$DIRECCIOIN)
BASE_DATOS_PSOCIALES_JULIO2021$ZONA[x] <- NA
rm(x)
                #Remover zonas de Villa nueva
x<- grep("VILLA NUEVA",BASE_DATOS_PSOCIALES_JULIO2021$DIRECCIOIN)
BASE_DATOS_PSOCIALES_JULIO2021$ZONA[x] <- NA
rm(x)
                #Remover zonas de Chinautla
x<- grep("CHINAUTLA",BASE_DATOS_PSOCIALES_JULIO2021$DIRECCIOIN)
BASE_DATOS_PSOCIALES_JULIO2021$ZONA[x] <- NA
rm(x)
                #Remover zonas de San Juan Sacatepequez
x<- grep("SAN JUAN SACATEPEQUEZ",BASE_DATOS_PSOCIALES_JULIO2021$DIRECCIOIN)
BASE_DATOS_PSOCIALES_JULIO2021$ZONA[x] <- NA
rm(x)
                #Remover zonas de San José Pinula
x<- grep("SAN JOSÉ PINULA",BASE_DATOS_PSOCIALES_JULIO2021$DIRECCIOIN)
BASE_DATOS_PSOCIALES_JULIO2021$ZONA[x] <- NA
rm(x)
                #Remover zonas de San José Pinula
x<- grep("SAN JOSE PINULA",BASE_DATOS_PSOCIALES_JULIO2021$DIRECCIOIN)
BASE_DATOS_PSOCIALES_JULIO2021$ZONA[x] <- NA
rm(x)
                #Región
BASE_DATOS_PSOCIALES_JULIO2021$REGION <- NA
                        #Region 1
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==1] <- 1
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==5] <- 1
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==11] <- 1
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==21] <- 1
                        #Region 2
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==3] <- 2
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==6] <- 2
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==14] <- 2
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==19] <- 2
                        #Region 3
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==7] <- 3
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==12] <- 3
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==13] <- 3
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==15] <- 3
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==16] <- 3
                        #Region 4
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==17] <- 4
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==18] <- 4
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==24] <- 4
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==25] <- 4
                        #Region 5
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==2] <- 5
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==4] <- 5
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==8] <- 5
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==9] <- 5
BASE_DATOS_PSOCIALES_JULIO2021$REGION[BASE_DATOS_PSOCIALES_JULIO2021$ZONA==10] <- 5
BASE_DATOS_PSOCIALES_JULIO2021$REGION <- as.factor(BASE_DATOS_PSOCIALES_JULIO2021$REGION)
        #Establecer cuantos correos y teléfonos tenemos
BASE_DATOS_PSOCIALES_JULIO2021$CORREO_ALUMNO[BASE_DATOS_PSOCIALES_JULIO2021$CORREO_ALUMNO==""] <- NA
BASE_DATOS_PSOCIALES_JULIO2021$TELEFONO[BASE_DATOS_PSOCIALES_JULIO2021$TELEFONO==""] <- NA
                #Nueva variable
BASE_DATOS_PSOCIALES_JULIO2021$COMUNICACION <- NA
BASE_DATOS_PSOCIALES_JULIO2021$COMUNICACION[is.na(BASE_DATOS_PSOCIALES_JULIO2021$TELEFONO) &
                                                    is.na(BASE_DATOS_PSOCIALES_JULIO2021$CORREO_ALUMNO)] <- "Sin medio de contacto"
BASE_DATOS_PSOCIALES_JULIO2021$COMUNICACION[!is.na(BASE_DATOS_PSOCIALES_JULIO2021$TELEFONO) &
                                                    is.na(BASE_DATOS_PSOCIALES_JULIO2021$CORREO_ALUMNO)] <- "Sólo teléfono"
BASE_DATOS_PSOCIALES_JULIO2021$COMUNICACION[is.na(BASE_DATOS_PSOCIALES_JULIO2021$TELEFONO) &
                                                    !is.na(BASE_DATOS_PSOCIALES_JULIO2021$CORREO_ALUMNO)] <- "Sólo correo"
BASE_DATOS_PSOCIALES_JULIO2021$COMUNICACION[!is.na(BASE_DATOS_PSOCIALES_JULIO2021$TELEFONO) &
                                                    !is.na(BASE_DATOS_PSOCIALES_JULIO2021$CORREO_ALUMNO)] <- "Correo y teléfono"
BASE_DATOS_PSOCIALES_JULIO2021$COMUNICACION <- 
        as.factor(BASE_DATOS_PSOCIALES_JULIO2021$COMUNICACION)
BASE_DATOS_PSOCIALES_JULIO2021$COMUNICACION <- 
        factor(BASE_DATOS_PSOCIALES_JULIO2021$COMUNICACION,
               levels = c("Sin medio de contacto","Sólo correo",
                          "Sólo teléfono","Correo y teléfono"))