library(tidyverse)
library(eeptools)
library(readr)
library(genero)
#Cargar datos
BASE_DATOS_PSOCIALES_JULIO2021 <- 
        read.csv("~/R Projects/Reporte_Gerencia_BU_2021/Datos/BASE DATOS PSOCIALES B U JULIO2021.csv", header=FALSE)
#Renombrar las variables de la base de datos para conservar DPI
x <- BASE_DATOS_PSOCIALES_JULIO2021[1,]
BASE_DATOS_PSOCIALES_JULIO2021 <- BASE_DATOS_PSOCIALES_JULIO2021[-1,]
colnames(BASE_DATOS_PSOCIALES_JULIO2021) <- x[1,]
rm(x)
#Tipificar variables
BASE_DATOS_PSOCIALES_JULIO2021$ASIGNACION <- gsub(",","",BASE_DATOS_PSOCIALES_JULIO2021$ASIGNACION)
BASE_DATOS_PSOCIALES_JULIO2021$ASIGNACION <- as.factor(BASE_DATOS_PSOCIALES_JULIO2021$ASIGNACION)

BASE_DATOS_PSOCIALES_JULIO2021$ANIO <- gsub(",","",BASE_DATOS_PSOCIALES_JULIO2021$ANIO)
BASE_DATOS_PSOCIALES_JULIO2021$ANIO <- as.factor(BASE_DATOS_PSOCIALES_JULIO2021$ANIO)

BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA[BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA=="CONVIVENVIA"] <- "CONVIVENCIA"
BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA[BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA=="MUNIEDUCA MOVIL"] <- "MUNIEDUCA MÓVIL"
BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA[BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA=="TECNICO PRODUCTIVO"] <- "TÉCNICO PRODUCTIVO"
BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA <- as.factor(BASE_DATOS_PSOCIALES_JULIO2021$PROGRAMA)

BASE_DATOS_PSOCIALES_JULIO2021$CUI<- trimws(BASE_DATOS_PSOCIALES_JULIO2021$CUI, which = "both")
BASE_DATOS_PSOCIALES_JULIO2021$CUI[nchar(BASE_DATOS_PSOCIALES_JULIO2021$CUI)==12] <- NA
        #Fecha de nacimiento con formato fecha
BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO <- format(as.POSIXct(BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO,
                                                        format='%m/%d/%Y %H:%M:%S'),format='%m/%d/%Y')
BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO<- as.Date(BASE_DATOS_PSOCIALES_JULIO2021$FECHA_NACIMIENTO,
                                                          format = "%m/%d/%Y")
        #Limpieza de sexo
                #Obtener los que no tienen sexo y agregárselo
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[BASE_DATOS_PSOCIALES_JULIO2021$SEXO==""] <- NA
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[BASE_DATOS_PSOCIALES_JULIO2021$SEXO=="A"] <- NA
SIN_SEXO <- BASE_DATOS_PSOCIALES_JULIO2021 %>%
        filter(is.na(BASE_DATOS_PSOCIALES_JULIO2021$SEXO)) %>%
        select(CUI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,SEXO) %>%
        distinct(CUI,.keep_all=TRUE)
SIN_SEXO$SEXO <- genero(SIN_SEXO$PRIMER_NOMBRE,lang = "es")
SIN_SEXO$SEXO[SIN_SEXO$SEXO=="female"] <- "F"
SIN_SEXO$SEXO[SIN_SEXO$SEXO=="male"] <- "M"
                #Corregir el sexo de los posibles
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[BASE_DATOS_PSOCIALES_JULIO2021$CUI==2940568380101] <- "F"
                #Filtrado y reconstruccion de la bse de datos
COMPLETA_SIN_SEXO <- BASE_DATOS_PSOCIALES_JULIO2021 %>%
        filter(is.na(BASE_DATOS_PSOCIALES_JULIO2021$SEXO)) %>%
        select(CUI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,SEXO)
COMPLETA_SIN_SEXO$SEXO<- SIN_SEXO$SEXO[match(COMPLETA_SIN_SEXO$CUI,SIN_SEXO$CUI)]
x<- which(is.na(BASE_DATOS_PSOCIALES_JULIO2021$SEXO)) 
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[x] <- COMPLETA_SIN_SEXO$SEXO
rm(COMPLETA_SIN_SEXO)
rm(SIN_SEXO)
rm(x)
                #Cambio de notacion y convertir a factor
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[BASE_DATOS_PSOCIALES_JULIO2021$SEXO=="F"] <- "Femenino"
BASE_DATOS_PSOCIALES_JULIO2021$SEXO[BASE_DATOS_PSOCIALES_JULIO2021$SEXO=="M"] <- "Masculino"
BASE_DATOS_PSOCIALES_JULIO2021$SEXO <- as.factor(BASE_DATOS_PSOCIALES_JULIO2021$SEXO)






